services:
- type: web
  name: kolovrat-tg-bot
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  envVars:
  - key: BOT_TOKEN
    sync: false
  - key: WEBHOOK_SECRET
    generateValue: true
  - key: WEBHOOK_BASE
    sync: false
